In [ ]:
from sklearn import feature_extraction, model_selection
import pandas as pd

In [ ]:
def get_data():
  return pd.read_csv('/data.csv', index_col=0)

In [ ]:
data = get_data()
data

,cleaned_text,anxiety,normal,stress,lonely,translated_text
0,alone time precious love alone want spend time...,1,0,0,0,один время драгоценный люблю один хотеть прово...
1,wanna vent dont feel safe venting cause right ...,1,0,0,0,хочу вентиляция не Чувствовать сейф вентиляция...
2,shit brings back cause know love care even fee...,1,0,0,0,дерьмо приносит назад причина знать люблю забо...
3,tweet purely afraid go lonely nigga dont like ...,1,0,0,0,твит чисто боятся идти Одинокий ниггер не нрав...
4,im gonna take shower im sure help calm know ca...,1,0,0,0,я собираюсь брать душ я Конечно помощь спокойс...
...,...,...,...,...,...,...
795,dont think need dare,0,0,0,1,не считать необходимость осмелиться
796,need trey songz understand,0,0,0,1,необходимость трей песни понимать
797,need fold clothes cook sew dont dont feel like...,0,0,0,1,необходимость складывать одежда готовить пищу ...
798,honestly wouldnt able hadnt already carefully ...,0,0,0,1,честно говоря не будет способный не было уже о...
799,deal w shit alone long ik ima good,0,0,0,1,по рукам ш дерьмо один длинный ик има хорошо

In [ ]:
y = pd.DataFrame([[row.anxiety, row.normal, row.stress, row.lonely] for index, row in data.iterrows()])
features = ['translated_text']
X = data[features]
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
X= tf.fit_transform(data['translated_text'])
train_x, test_x, train_y, test_y = model_selection.train_test_split(X, y, test_size=0.3)
train_y.head()

     0  1  2  3
696  0  0  0  1
556  0  0  1  0
540  0  0  1  0
629  0  0  0  1
364  0  1  0  0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.models import load_model

In [ ]:
model = keras.Model(inputs=inputs, outputs=outputs)
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
model.fit(train_x, train_y, epochs=10)

In [ ]:
probability_model = tf.keras.Sequential([model, 
                                         tf.keras.layers.Softmax()])
predictions = probability_model.predict(test_x)
np.argmax(predictions[0])